services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    networks:
      - beebrain_net

  beebrain:
    build:
      context: .
      dockerfile: Dockerfile.beebrain
    ports:
      - "8080:8080"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}
      - SLACK_BOT_USER=${SLACK_BOT_USER}
    depends_on:
      - ollama
    networks:
      - beebrain_net

  pull-llama3:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: ["ollama"]
    command: ["pull", "llama3"]
    profiles: ["pull-models"]
    networks:
      - beebrain_net

volumes:
  ollama_data:

networks:
  beebrain_net:
    driver: bridge 